version: '3.9'

services:
  fastapi:
    build: 
      dockerfile: docker/Dockerfile
    command: "uvicorn app.main:app --host=0.0.0.0 --port=8000 --reload"
    ports:
      - "5000:8000"
    develop:
      watch:
        - action: sync
          path: ./app
    networks:
      - midas-network

  was:
    image: iampingu99/project-backend
    ports:
      - "8000:8080"
    networks:
      - midas-network

  # front-end:
  #   image: 
  #   command: 
  #   ports:
  #     - "7000:"
  #   networks:
  #     - midas-network

networks:
  midas-network:
