#FastAPI Docker Image Build and Push to DockerHub
name: Docker Image 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Install Python & Dependencises
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install Dependencises
        run: |
          pip install -r requirements.txt

  docker:
    name: Build & Push to DockerHub
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name : Docker Image Build & Push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./docker/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}

    env:
      DOCKER_IMAGE_NAME: extension
