#FastAPI Docker Image Build and Push to DockerHub
name: MIDAS-EXTENSION github actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - names: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python & Install Dependencises
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
        run: |
          pip install -r requirements.txt

      - name: Python Install Test
        run: python3 -h
      
      - name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Image Build
        run: |
          docker build \
          --tag ${{ secrets.DOKCERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest \
          .
      
      - name: Docker Image Push
        run: |
          docker push \
          ${{ secrets.DOKCERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest

    env:
      DOCKER_IMAGE_NAME: midas-extension
